#ifndef FIXED_MEMORY_ADDRESSES_H
#define FIXED_MEMORY_ADDRESSES_H

#define VENDOR_BASIC_DEMO_IN_DATA_BUFFER_ADDRESS      @0x0A0
#define VENDOR_BASIC_DEMO_OUT_DATA_BUFFER_0_ADDRESS     @0x120
#define VENDOR_BASIC_DEMO_OUT_DATA_BUFFER_1_ADDRESS     @0x1A0
#define VENDOR_BASIC_DEMO_OUT_DATA_BUFFER_2_ADDRESS     @0x220
#define CONTROL_BUFFER_ADDRESS_TAG                    @0x2A0

#endif //FIXED_MEMORY_ADDRESSES